---
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-build-mod
        alias: build
      - id: go-mod-tidy
        alias: tidy
      - id: go-fmt
        alias: fmt
        args: [-s, -w]
      - id: go-test-mod
        alias: test

  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt

  - repo: local
    hooks:
      - id: golangci-lint
        name: Go Lint (golangci-lint)
        entry: golangci-lint run
        language: system
        files: \.go$
        pass_filenames: false

      - id: markdownlint-cli2
        name: Markdown Lint
        entry: markdownlint-cli2
        language: node
        files: \.md$

      - id: actionlint
        name: GitHub Actions Lint
        entry: actionlint
        language: system
        files: ^\.github/workflows/.*\.ya?ml$

      - id: editorconfig-checker
        name: EditorConfig Checker
        entry: editorconfig-checker
        args: [-format, gcc]
        language: system
        files: .

  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake
        name: Makefile Linter
        files: ^Makefile$
