# f2b Makefile

.PHONY: help all build test lint fmt fmt-check clean install
.PHONY: ci ci-coverage test-verbose test-coverage update-deps fmt-md
.PHONY: docs-api
.PHONY: lint-go lint-md lint-yaml lint-actions lint-make
.PHONY: security dev-setup prek-setup
.PHONY: release-dry-run release release-snapshot release-check _check-tag

# Tool versions (managed by Renovate)
# renovate: datasource=go depName=github.com/goreleaser/goreleaser/v2
GORELEASER_VERSION := v2.18.0
# renovate: datasource=go depName=github.com/golangci/golangci-lint/v2/cmd/golangci-lint
GOLANGCI_LINT_VERSION := v2.13.2
# renovate: datasource=go depName=github.com/google/yamlfmt/cmd/yamlfmt
YAMLFMT_VERSION := v0.21.0
# renovate: datasource=go depName=github.com/rhysd/actionlint/cmd/actionlint
ACTIONLINT_VERSION := v1.7.12
# renovate: datasource=go depName=golang.org/x/tools/cmd/goimports
GOIMPORTS_VERSION := v0.42.0
# renovate: datasource=go depName=github.com/editorconfig-checker/editorconfig-checker/v3/cmd/editorconfig-checker
EDITORCONFIG_CHECKER_VERSION := v3.11.3
# renovate: datasource=go depName=github.com/securego/gosec/v2/cmd/gosec
GOSEC_VERSION := v2.29.0
# renovate: datasource=go depName=honnef.co/go/tools/cmd/staticcheck
STATICCHECK_VERSION := v0.8.1
# renovate: datasource=go depName=github.com/mgechev/revive
REVIVE_VERSION := v1.16.0
# renovate: datasource=go depName=github.com/checkmake/checkmake/cmd/checkmake
CHECKMAKE_VERSION := v0.3.2
# renovate: datasource=go depName=github.com/segmentio/golines
GOLINES_VERSION := v0.13.0
# renovate: datasource=npm depName=markdownlint-cli2
MARKDOWNLINT_CLI2_VERSION := 0.23.2
# renovate: datasource=go depName=github.com/princjef/gomarkdoc/cmd/gomarkdoc
GOMARKDOC_VERSION := v1.1.0
GOMARKDOC := go run github.com/princjef/gomarkdoc/cmd/gomarkdoc@$(GOMARKDOC_VERSION)
# renovate: datasource=github-releases depName=j178/prek
PREK_VERSION := v0.5.2

# Public API packages documented by `make docs-api` (skips the root main package).
API_PACKAGES := cmd constants fail2ban

# Default target
help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  %-15s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

all: ci ## Run all CI checks (same as ci target)
	@echo "All checks completed"

# Build targets
build: ## Build the f2b binary
	go build -ldflags "-X github.com/ivuorinen/f2b/cmd.Version=dev" -o f2b .

install: ## Install f2b globally from the local working copy
	go install -ldflags "-X github.com/ivuorinen/f2b/cmd.Version=dev" .

# Testing targets
test: ## Run all tests
	go test -race ./...

test-verbose: ## Run tests with verbose output
	go test -v ./...

test-coverage: ## Run tests with coverage report
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out -o coverage.html

update-deps: ## Update Go dependencies to latest patch versions
	go get -u=patch ./...
	go mod tidy
	go mod verify
	@go list -u -m all | grep '\[' || true

# Documentation targets
docs-api: ## Generate public API docs (markdown) into docs/api/ for GitHub Pages
	@mkdir -p docs/api
	@printf '# f2b API Reference\n\nGenerated by `make docs-api`; do not edit by hand.\n\n' > docs/api/index.md
	@for pkg in $(API_PACKAGES); do $(GOMARKDOC) --output docs/api/$$pkg.md ./$$pkg \
		&& echo "- [\`$$pkg\`]($$pkg.md)" >> docs/api/index.md || exit 1; done

# Code quality targets
fmt: ## Format Go code
	gofmt -w .

fmt-check: ## Fail if any Go file is not gofmt-formatted (does not modify files)
	@unformatted="$$(gofmt -l .)"; [ -z "$$unformatted" ] || \
		{ echo "The following files are not gofmt-formatted:"; echo "$$unformatted"; exit 1; }

fmt-md: ## Format Markdown files
	@prek run mdformat --all-files

lint: ## Run all linters using prek (preferred method)
	@prek run --all-files

lint-go: ## Run only Go linters
	go vet ./...
	go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION) run --timeout=5m

lint-md: ## Run only Markdown linter
	npx --yes markdownlint-cli2@$(MARKDOWNLINT_CLI2_VERSION) "*.md" "**/*.md" "!docs/api/**"

lint-yaml: ## Run only YAML linter
	go run github.com/google/yamlfmt/cmd/yamlfmt@$(YAMLFMT_VERSION) -lint .

lint-actions: ## Run only GitHub Actions linter
	go run github.com/rhysd/actionlint/cmd/actionlint@$(ACTIONLINT_VERSION) .github/workflows/*.yml

lint-make: ## Run only Makefile linter
	go run github.com/checkmake/checkmake/cmd/checkmake@$(CHECKMAKE_VERSION) Makefile

# CI targets
# CI must VERIFY formatting, not rewrite it: `gofmt -w` mutates the tree and
# always exits 0, so a formatting violation would pass CI silently. fmt-check
# fails instead.
ci: fmt-check lint test ## Run all CI checks (verify format, lint, test)

ci-coverage: fmt-check lint test-coverage ## Run CI checks with coverage

# Security targets
security: ## Run security checks
	go run github.com/securego/gosec/v2/cmd/gosec@$(GOSEC_VERSION) ./...

# Cleanup targets
clean: ## Clean build artifacts
	rm -f f2b coverage.out coverage.html
	go clean

# Development targets
dev-setup: prek-setup ## Set up development environment

# An installed prek satisfies `command -v` at ANY version, so a stale local
# binary would silently disagree with the version CI pins. Warn on mismatch
# rather than reinstall: prek is often managed by mise/brew, and overwriting a
# developer's toolchain is worse than the drift it fixes.
prek-setup: ## Install and configure prek git hooks
	@command -v prek >/dev/null 2>&1 || curl --proto '=https' --tlsv1.2 -LsSf \
		https://github.com/j178/prek/releases/download/$(PREK_VERSION)/prek-installer.sh | sh
	@have="$$(prek --version 2>/dev/null | awk '{print $$NF}')"; want="$(PREK_VERSION:v%=%)"; \
		[ "$$have" = "$$want" ] || printf 'warning: prek %s installed, pinned is %s\n' "$$have" "$$want" >&2
	@prek install

# Release targets
release-dry-run: ## Test release process without creating artifacts
	@VERSION=$$(git describe --tags --exact-match 2>/dev/null || echo "v0.0.0-dev"); \
	echo "Building version: $$VERSION"; \
	go build -ldflags "-X github.com/ivuorinen/f2b/cmd.Version=$$VERSION" -o f2b-test . && rm -f f2b-test

release: _check-tag ## Create a new release using GoReleaser
	go run github.com/goreleaser/goreleaser/v2@$(GORELEASER_VERSION) release --clean

_check-tag: ## Internal: Check if a git tag exists
	@if [ -z "$$(git describe --tags --exact-match 2>/dev/null)" ]; then \
		echo "Error: No tag found. Please create a tag first (e.g., git tag v1.0.0)"; \
		exit 1; \
	fi

release-snapshot: ## Create a snapshot release (no tag required)
	go run github.com/goreleaser/goreleaser/v2@$(GORELEASER_VERSION) release --snapshot --clean

release-check: ## Check if GoReleaser configuration is valid
	go run github.com/goreleaser/goreleaser/v2@$(GORELEASER_VERSION) check
