---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: govulncheck

on:
  push:
    branches: [master, main]
  schedule:
    - cron: "0 6 * * 1" # Every Monday at 06:00

permissions:
  contents: read

jobs:
  govulncheck:
    name: Scan for known vulnerabilities
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          go-version-file: go.mod
