---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: ivuorinen/actions/sync-labels@de31e11dda6488eabe95e951ebb61c6d9d500865 # v2026.06.30
